name: CI/CD Pipelines

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Check for Git
        run: |
          if ! command -v git &> /dev/null; then
              echo "Git not found, installing..."
              sudo apt-get update
              sudo apt-get install -y git
          else
              echo "Git is already installed."
          fi

      - name: Check for Maven
        run: |
          if ! command -v mvn &> /dev/null; then
              echo "Maven not found, installing..."
              sudo apt-get update
              sudo apt-get install -y maven
          else
              echo "Maven is already installed."
          fi

  build:
    runs-on: self-hosted
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build with Maven
        run: ./mvnw -B package

  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: ./mvnw test

  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy application
        env:
          DEPLOY_SERVER: '103.172.26.41'
          DEPLOY_PORT: '8080'
          DEPLOY_USER: 'daim'
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          scp -i ~/.ssh/id_ed25519 spring-petclinic-3.3.0-SNAPSHOT.jar daim@103.172.26.41:/home/daim/spring-petclinic/
          
          ssh -i ~/.ssh/id_ed25519 daim@103.172.26.41 "nohup java -jar /home/daim/spring-petclinic/spring-petclinic-3.3.0-SNAPSHOT.jar > /dev/null 2>&1 &"

          for i in {1..30}; do
            if curl -s http://$DEPLOY_SERVER:$DEPLOY_PORT > /dev/null; then
              echo "Application is up!"
              break
            else
              echo "Application is not up yet, retrying in 10 seconds..."
              sleep 10
            fi
          done
